import { bag, beatz, beatz2, black, camera, chair, coat, console, console1, console2, console4, consoleImg, dogFood, gameConsole, gamepad, img1, iphone, iphone1, iphone2, iphone3, jacket, keyboard, kidCar, laptop, monitor, oak, patso, perfumeSet, polo, red, reebook, shelf, sneakers, soccerBoot, sofa, speaker, tonny, user1, user2 } from "./images";

export const allProducts = [
    {
        id: "flsh-00-1",
        category: "gaming",
        tags: "Gaming, Xbox, Computers",
        name: "HAVIT HV-G92 Gamepad",
        seller: "Havit",
        isNew: false,
        price: 5640,
        oldPrice: 9400,
        discount: 40,
        stock: 20,
        ratings: 4.6,
        ratingsCount: 88,
        img: gamepad,
        shipping: 2,
        quantity: 24,
        description: "Introducing the HAVIT HV-G92 Gamepad, a cutting-edge entertainment device that combines elegance with exceptional durability. This remarkable product boasts a sleek and stylish design, perfectly crafted to enhance your gaming experience",
        desc: "The HAVIT HV-G92 Gamepad is meticulously engineered to provide seamless functionality and deliver unparalleled gaming adventures. With its state-of-the-art technology, this console offers a vast library of captivating games, guaranteeing endless entertainment for both casual and avid gamers alike. Not only does the HAVIT HV-G92 Gamepad excel in performance, but it also exudes sophistication. Its sleek exterior showcases a modern aesthetic that effortlessly complements any home entertainment setup. Whether placed in a living room or bedroom, this console adds a touch of elegance to your space. Furthermore, the HAVIT HV-G92 Gamepad is designed with durability in mind.",
        desc2: "Built to withstand the rigors of intense gaming sessions, it is constructed using premium materials that ensure its longevity. Rest assured that this console will accompany you on your gaming journey for years to come.",
        reviews: [
            {
                id: 1,
                profile: user1,
                name: 'Harry Wilson Thomas',
                date: '20 June, 2023',
                ratings: 4.0,
                comment: "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. It was compatible with my Xbox."
            },

            {
                id: 2,
                profile: user2,
                name: 'Christine Ann',
                date: '28 June, 2023',
                ratings: 4.5,
                comment: "I bought it 3 weeks ago and now come back just to say “Awesome Product”. I really enjoy it. It was compatible with my Xbox."
            },
        ]
    },

    {
        id: "flsh-00-2",
        category: "computers",
        tags: "Computers, AK",
        name: "AK-900 Wired Keyboard",
        seller: "AK",
        isNew: false,
        price: 6000,
        oldPrice: 12000,
        discount: 50,
        stock: 15,
        ratings: 4.1,
        ratingsCount: 75,
        img: keyboard,
        shipping: 1,
        quantity: 3
    },

    {
        id: "flsh-00-3",
        category: "computers",
        name: "LCD Gaming Monitor",
        tags: "HP, Computers",
        seller: "HP",
        isNew: true,
        price: 41496,
        oldPrice: 54600,
        discount: 24,
        stock: 8,
        ratings: 4.5,
        ratingsCount: 75,
        img: monitor,
        shipping: 2,
        quantity: 10
    },
    
    {
        id: "flsh-00-4",
        category: "home & office",
        tags: "Home, Office",
        name: "5-Series Comfort Chair",
        seller: "5-Series",
        isNew: false,
        price: 25916,
        oldPrice: 41800,
        discount: 38,
        stock: 18,
        ratings: 4.0,
        ratingsCount: 106,
        img: chair,
        shipping: 1,
        quantity: 22
    },

    

    {
        id: "flsh-00-5",
        category: "men's fashion",
        tags: "Men, Jacket, Fashion",
        name: "Quilted Satin Jacket",
        seller: "Nike",
        isNew: true,
        price: 26510,
        oldPrice: 48200,
        stock: 9,
        discount: 45,
        ratings: 4.6,
        ratingsCount: 43,
        img: jacket,
        shipping: 1,
        quantity: 8,
        hasSize: true,
        size: 'S',
        productNumber: 0,
        description: "Introducing our Quilted Satin Jacket - the epitome of affordable fashion that effortlessly combines style and comfort. Crafted with utmost precision, this jacket is designed to elevate your wardrobe without breaking the bank.",
        desc: "Not only does the Quilted Satin Jacket exude style, but it also prioritizes your comfort. The lightweight construction allows for easy layering, keeping you cozy without feeling bulky. The satin material provides a gentle warmth, making it suitable for year-round wear. Say goodbye to sacrificing comfort for fashion - with this jacket, you can have the best of both worlds. But what truly sets the Quilted Satin Jacket apart is its affordability. We believe that everyone deserves to feel confident and stylish, without having to empty their wallets. That's why we've carefully priced this jacket to be accessible to all fashion enthusiasts. Now, you can effortlessly upgrade your wardrobe without breaking the bank.",
        desc2: "So why wait? Embrace the elegance and comfort of our Quilted Satin Jacket today. With its affordable price, stylish design, and unbeatable comfort, this jacket is a must-have addition to any fashion-forward individual's collection. Experience the perfect blend of affordability, style, and comfort - because you deserve it."
    },

    {
        id: "flsh-00-6",
        category: "computers",
        tags: "Laptop, Computing, ASUS",
        name: "ASUS FHD Gaming Laptop",
        seller: "ASUS",
        isNew: false,
        price: 455000,
        oldPrice: 650000,
        discount: 30,
        stock: 16,
        ratings: 3.9,
        ratingsCount: 18,
        img: laptop,
        shipping: 2,
        quantity: 11
    },

    {
        id: "flsh-00-7",
        category: "women's fashion",
        tags: "Women, Fashion, Accessories, Gucci",
        name: "Guuci Duffel Bag",
        seller: "Gucci",
        isNew: true,
        price: 66000,
        oldPrice: 120000,
        discount: 45,
        stock: 2,
        ratings: 4.8,
        ratingsCount: 78,
        img: bag,
        shipping: 2,
        quantity: 4,
        description: "Designed to exude elegance and sophistication, our Gucci Duffel Bag is perfect for any occasion. Whether you're headed to a formal event, a casual outing with friends, or a professional meeting, this bag will effortlessly elevate your style.",
        desc: "Made from high-quality materials, this handbag is built to last. Its sturdy construction ensures durability, allowing you to carry your essentials with confidence. The spacious interior provides ample room for your belongings, including your wallet, phone, keys, and makeup essentials. Not only is this bag practical, but it also boasts a beautiful design. The intricate detailing and exquisite craftsmanship make it a true work of art. The carefully chosen color palette adds a touch of vibrancy, allowing you to make a bold fashion statement wherever you go. With its adjustable and comfortable straps, you can wear this Gucci Duffel Bag in a way that suits your personal preference. Whether you prefer to carry it as a handbag or sling it over your shoulder, this versatile accessory will adapt to your needs effortlessly.",
        desc2: "Invest in this Gucci Duffel Bag today and experience the perfect blend of style and functionality. It is a timeless piece that will never go out of fashion, making it a valuable addition to your wardrobe. Don't miss out on the opportunity to own this beautiful product that will surely turn heads wherever you carry it!"
    },

    {
        id: "flsh-00-8",
        category: "cameras",
        tags: "CANON, Camera, Photography",
        name: "CANON EOS DSLR Camera",
        seller: "CANON",
        isNew: true,
        price: 263000,
        oldPrice: 280000,
        discount: 45,
        stock: 9,
        ratings: 3.8,
        ratingsCount: 28,
        img: camera,
        shipping: 1,
        quantity: 17
    },

    {
        id: "flsh-00-9",
        category: "animals & pets",
        tags: "Animals, Pets",
        name: "Breed Dry Dog Food",
        seller: "Cesar",
        isNew: false,
        price: 37500,
        oldPrice: 44000,
        discount: 45,
        stock: 2,
        ratings: 4.2,
        ratingsCount: 28,
        img: dogFood,
        shipping: 1,
        quantity: 3
    },

    {
        id: "flsh-00-10",
        category: "men's fashion",
        tags: "Men, Jacket, Fashion, Winter",
        name: "The north coat",
        seller: "Cesar",
        isNew: true,
        price: 18000,
        oldPrice: 24000,
        discount: 45,
        stock: 11,
        ratings: 3.5,
        ratingsCount: 28,
        img: coat,
        shipping: 1,
        quantity: 6,
        hasSize: true,
        size: 'S',
        productNumber: 1,
        description: "With its sleek and timeless design, The North Coat is the epitome of elegance. Its tailored silhouette effortlessly enhances your overall look, making it suitable for various occasions, from casual outings to formal events. The coat's exquisite craftsmanship and attention to detail ensure that you will always make a lasting impression.",
        desc: "Winter can be harsh, but with The North Coat, you can brave the elements with confidence. The premium materials used in its construction provide exceptional insulation, effectively shielding you from the biting cold. Whether you're strolling through the city streets or exploring the great outdoors, this coat will keep you snug and protected. Comfort is paramount, and The North Coat delivers on this front as well. Its carefully selected fabrics offer a soft and plush feel against your skin, ensuring maximum comfort throughout the day. The coat's impeccable tailoring allows for ease of movement, allowing you to go about your daily activities without any restrictions.",
        desc2: "Invest in The North Coat, and experience the perfect blend of style, winter functionality, and comfort. Embrace the colder months with confidence, knowing that you are wrapped in a coat that not only keeps you warm but also exudes sophistication. Elevate your winter wardrobe and make a statement with The North Coat - the ultimate companion for the discerning individual seeking both style and cozy warmth."
    },

    {
        id: "flsh-00-11",
        category: "kids & toys",
        tags: "Toys, Kids",
        name: "Kids Electric Car",
        seller: "BMW",
        isNew: true,
        price: 45000,
        oldPrice: 50000,
        discount: 45,
        stock: 3,
        ratings: 4.4,
        ratingsCount: 28,
        img: kidCar,
        shipping: 1,
        quantity: 12
    },

    {
        id: "flsh-00-12",
        category: "men's fashion",
        tags: "Nike, Boots, Shoes",
        name: "Jr. Zoom Soccer Cleats",
        seller: "Nike",
        isNew: false,
        price: 25999,
        oldPrice: 38000,
        discount: 45,
        stock: 8,
        ratings: 4.1,
        ratingsCount: 28,
        img: soccerBoot,
        shipping: 1,
        quantity: 7,
        isShoe: true,
        size: 43,
        productNumber: 3,
        description: "Introducing the Jr. Zoom Soccer Cleats, a stunning and lightweight footwear option designed specifically for young soccer enthusiasts. Crafted with utmost precision and attention to detail, these soccer cleats are the epitome of elegance and functionality.",
        desc: "The Jr. Zoom Soccer Cleats boast a captivating aesthetic that is sure to turn heads on the field. The sleek design, coupled with vibrant color options, adds a touch of sophistication to your child's soccer gear. Whether they are participating in a friendly match or a competitive tournament, these cleats will undoubtedly make a stylish statement. Not only do these cleats excel in appearance, but they also prioritize comfort and performance. Engineered with lightweight materials, they provide a feather-like sensation, allowing young players to move swiftly and effortlessly across the pitch. The snug fit ensures optimal agility, enabling precise footwork and quick direction changes. Durability is a key feature of the Jr. Zoom Soccer Cleats.",
        desc2: "Constructed with high-quality materials, these cleats are built to withstand the rigors of intense gameplay. They offer exceptional traction and grip, ensuring maximum stability and preventing slips or falls during critical moments of the game. Furthermore, the Jr. Zoom Soccer Cleats prioritize the safety of young athletes. The design includes reinforced toe caps and ankle support, providing added protection against potential injuries. With these cleats, parents can have peace of mind knowing that their child's feet are well-guarded on the field."
        
    },

    {
        id: "flsh-00-13",
        category: "home & office",
        tags: "Office, Home",
        name: "Small BookShelf",
        seller: "Acry",
        isNew: false,
        price: 15000,
        oldPrice: 22000,
        discount: 45,
        stock: 18,
        ratings: 4.5,
        ratingsCount: 38,
        img: shelf,
        shipping: 1,
        quantity: 5
    },

    {
        id: "flsh-00-14",
        category: "sound systems",
        tags: "Electronic, Sound",
        name: "RGB liquid CPU Coolerf",
        seller: "Panasonic",
        isNew: false,
        price: 85000,
        oldPrice: 99000,
        discount: 45,
        stock: 4,
        ratings: 3.8,
        ratingsCount: 60,
        img: speaker,
        shipping: 1,
        quantity: 10
    },

    {
        id: "flsh-00-15",
        category: "gaming",
        tags: "Gaming, UCOM, Computing",
        name: "GP11 Shooter USB Gamepad",
        seller: "UCOM",
        isNew: true,
        price: 12500,
        oldPrice: 17500,
        discount: 45,
        stock: 6,
        ratings: 4.5,
        ratingsCount: 24,
        img: gameConsole,
        shipping: 1,
        quantity: 3,
        description: "Equipped with a user-friendly interface, the GP11 Shooter USB Gamepad makes navigating through menus and settings a breeze. Its intuitive controls and responsive buttons ensure that you're always in complete control, allowing you to unleash your gaming skills with precision and finesse.",
        desc: "With its cutting-edge technology and innovative features, the GP11 Shooter USB Gamepad offers an immersive gaming experience like no other. Dive into a world of stunning graphics, seamless gameplay, and mind-blowing sound quality that will transport you to the heart of the action. Get ready to lose yourself in the captivating worlds of your favorite games like never before. Equipped with a user-friendly interface, the GP11 Shooter USB Gamepad makes navigating through menus and settings a breeze. Its intuitive controls and responsive buttons ensure that you're always in complete control, allowing you to unleash your gaming skills with precision and finesse.",
        desc2: "Whether you're a fan of high-octane racing games, adrenaline-pumping shooters, or immersive role-playing adventures, the GP11 Shooter USB Gamepad is your gateway to endless entertainment. It's time to level up your gaming experience and embrace a whole new world of excitement."
    },

    {
        id: "flsh-00-16",
        category: "beauty & luxury",
        tags: "Beauty, Women, Luxury, Cosmetics",
        name: "Curology Product Set",
        seller: "Curology",
        isNew: false,
        price: 14000,
        oldPrice: 22000,
        discount: 45,
        stock: 10,
        ratings: 4.8,
        ratingsCount: 33,
        img: perfumeSet,
        shipping: 2,
        quantity: 7
    },

    {
        id: "flsh-00-17",
        category: "gaming",
        tags: "Gaming, HAVIC, Computing",
        name: "Havic HV G-92 Gamepad",
        seller: "Havic",
        isNew: false,
        price: 29999,
        oldPrice: 40000,
        discount: 33,
        stock: 6,
        ratings: 4.8,
        ratingsCount: 41,
        img: console,
        imgDisplay: consoleImg,
        imgMark: [
            {
                imgMark1: console1,

            },
            
            {
                imgMark2: console2,
            },
            {
                imgMark3: console,

            },
            {
                imgMark4: console4,
                
            }
        ],
        shipping: 1,
        quantity: 3,
        description: "Introducing the Havic HV G-92 Gamepad - a sleek and durable marvel that will revolutionize your gaming experience! This extraordinary device is designed to take your gaming adventures to new heights, offering a perfect blend of style and resilience.",
        desc: "Crafted with utmost precision, the Havic HV G-92 Gamepad boasts a sleek and modern design that will effortlessly complement any gaming setup. Its smooth contours and minimalist aesthetics will make it the envy of all your friends. Whether you're a casual gamer or a hardcore enthusiast, this console is here to make a statement. But don't let its stunning appearance fool you - the Havic HV G-92 Gamepad is built to withstand the test of time. Constructed with durable materials, it can handle even the most intense gaming sessions without breaking a sweat. Say goodbye to worrying about accidental bumps or drops; this console is here to stay, ensuring you can focus solely on your gaming prowess.",
        desc2: "So why wait? Elevate your gaming setup with the Havic HV G-92 Gamepad - the epitome of sleekness and durability. Get ready to embark on unforgettable gaming journeys, leaving your competitors in awe and your friends begging for a turn. Unleash your inner gamer and let the Game Console be your ultimate companion in the world of gaming excellence."
    },

    {
        id: "flsh-00-18",
        category: "home & office",
        tags: "Home, Office",
        name: "Linc. Casual Table Tray",
        seller: "Linc.",
        isNew: true,
        price: 12500,
        oldPrice: 28000,
        discount: 40,
        stock: 16,
        ratings: 3.8,
        ratingsCount: 15,
        img: black,
        img2: red,
        img3: oak,
        image: black,
        shipping: 2,
        quantity: 7,
        hasColor: true,
        color: 'Black',
        description: "Behold the beauty of our Tray Table, designed to captivate your senses and elevate your living space. Crafted with meticulous attention to detail, this exquisite piece seamlessly blends style and functionality.",
        desc: "Weighing next to nothing, our Tray Table is a true featherweight champion. Its lightweight construction allows for effortless mobility, making it the perfect companion for any occasion. Whether you're hosting a cozy gathering or enjoying a peaceful evening alone, this table effortlessly adapts to your needs. But don't let its delicate appearance fool you - the Tray Table is built to last. Constructed with durable materials, it withstands the test of time, ensuring long-lasting enjoyment and reliability. You can trust that this table will be a faithful companion for years to come. What truly sets our Tray Table apart is its affordability. We believe that everyone deserves to enjoy a touch of elegance in their home without breaking the bank. That's why we've made it our mission to offer this exceptional piece at a price that won't strain your budget.",
        desc2: "Experience the joy of owning a high-quality, aesthetically pleasing table without compromising on your financial goals. Whether you're seeking a stylish addition to your living room, a convenient surface for your bedroom, or a versatile companion for outdoor activities, the Tray Table is the answer. Its timeless design effortlessly complements any decor, making it a versatile and adaptable piece for any space."


    },

    
    {
        id: "flsh-00-19",
        category: "men's fashion",
        tags: "Shirt, Polo shirt, Men, Fashion",
        name: "Greg Norman - Men's Shark Logo Golf Polo Shirt",
        seller: "Greg Norman",
        isNew: true,
        price: 8000,
        oldPrice: 14500,
        discount: 32,
        stock: 6,
        ratings: 4.5,
        ratingsCount: 28,
        img: polo,
        shipping: 1,
        quantity: 6,
        hasSize: true,
        size: 'S',
        productNumber: 2,
        description: "Designed to withstand the rigors of the golf course, the Greg Norman - Men's Shark Logo Golf Polo Shirt boasts exceptional durability. Its high-quality materials ensure that it will withstand countless swings and rounds, making it a reliable companion for every game.",
        desc: "Not only is this polo shirt durable, but it is also incredibly affordable. We understand the importance of offering a product that provides excellent value for your money. With the Greg Norman - Men's Shark Logo Golf Polo Shirt, you can enjoy top-notch quality without breaking the bank.  Furthermore, this polo shirt is exceptionally light, allowing for unrestricted movement and maximum comfort. Whether you're teeing off or celebrating a victorious putt, you'll appreciate the freedom of movement that this shirt provides. The iconic shark logo adds a touch of sophistication and style to your golfing attire, making you stand out on the green. It's a symbol of excellence and a testament to your passion for the sport.",
        desc2: "In conclusion, the Greg Norman - Men's Shark Logo Golf Polo Shirt is the perfect blend of style, comfort, and affordability. Whether you're a seasoned golfer or just starting out, this shirt is a must-have addition to your collection. So why wait? Step up your game with the Greg Norman - Men's Shark Logo Golf Polo Shirt and experience the confidence and style it brings to your golfing journey."
    },

    {
        id: "flsh-00-20",
        category: "men's fashion",
        tags: "Sneakers, Men, Nike",
        name: "Nike Core Sneakers Advantage Base",
        seller: "Nike",
        isNew: false,
        price: 26825,
        oldPrice: 45200,
        discount: 40,
        stock: 7,
        ratings: 4.3,
        ratingsCount: 18,
        img: sneakers,
        shipping: 1,
        quantity: 11,
        isShoe: true,
        size: 43,
        productNumber: 4,
        description: "Introducing the Nike Core Sneakers Advantage Base - a true embodiment of beauty and lightness! These sneakers are not just your ordinary footwear; they are a work of art designed to elevate your style game to new heights.",
        desc: "But it's not just about the aesthetics - the Nike Core Sneakers Advantage Base are built to perform. With a lightweight construction, they offer unparalleled comfort and flexibility, allowing you to move with ease and grace. The breathable materials used in their making ensure your feet stay fresh and cool, even during the most intense workouts. Featuring advanced cushioning technology, these sneakers provide exceptional support and shock absorption, making each step feel like walking on clouds. The durable outsole guarantees excellent traction, giving you the confidence to conquer any terrain with ease. Whether you're an athlete or a fashion enthusiast, the Nike Core Sneakers Advantage Base will be your ultimate companion. Step into a world of style, comfort, and performance with these remarkable sneakers.",
        desc2: "Elevate your footwear game and make a statement wherever you go. Choose the Nike Core Sneakers Advantage Base and embrace the beauty of lightness like never before.."
        
    },

    {
        id: "flsh-00-21",
        category: "women's fashion",
        tags: "Women, Fashion, Accessories, Bags",
        name: "Tonny Black - Shoulder bag-White-Plain",
        seller: "Tonny",
        isNew: true,
        price: 32700,
        oldPrice: 74000,
        discount: 45,
        stock: 4,
        ratings: 4.0,
        ratingsCount: 12,
        img: tonny,
        shipping: 2,
        quantity: 4,
        description: "The Tonny Black Shoulder bag-White-Plain is incredibly stylish, exuding an air of elegance and charm. Its sleek and minimalistic design makes it perfect for any occasion, be it a casual outing or a glamorous evening affair. ",
        desc: "Not only does this bag boast a captivating appearance, but it also offers practicality and functionality. The spacious interior provides ample room for all your essentials, ensuring you stay organized on the go. The adjustable shoulder strap allows for a comfortable and personalized fit, while the sturdy construction guarantees durability and longevity. Whether you're heading to a brunch with friends or attending a high-profile event, the Tonny Black Shoulder bag-White-Plain is your go-to accessory that will never disappoint. It effortlessly combines style and practicality, making it a true fashion statement.",
        desc2: "Upgrade your wardrobe with the Tonny Black Shoulder bag-White-Plain and embrace the world of fashion with confidence and panache. Get ready to turn heads and make a lasting impression wherever you go. Order yours today and experience the epitome of style!"
    },

    {
        id: "flsh-00-22",
        category: "women's fashion",
        tags: "Women, Fashion, Accessories, Bags",
        name: "Patso - Shoulder bag-White-Plain",
        seller: "Patso",
        isNew: true,
        price: 28999,
        oldPrice: 42222,
        discount: 45,
        stock: 4,
        ratings: 4.8,
        ratingsCount: 22,
        img: patso,
        shipping: 2,
        quantity: 4,
        description: "Introducing Patso - Shoulder bag-White-Plain, the epitome of style, coolness, and classiness! This trendy shoulder bag is designed to elevate your fashion game and make heads turn wherever you go. ",
        desc: "Crafted with utmost care, the Patso - Shoulder bag-White-Plain boasts a sleek and minimalist design that effortlessly complements any outfit. Its pristine white color adds a touch of elegance, making it a versatile accessory for both casual outings and formal occasions. But this bag is not just about looks - it's also highly functional. With its spacious interior, you can easily carry all your essentials without compromising on style. The adjustable shoulder strap ensures a comfortable fit, allowing you to wear it effortlessly throughout the day.",
        desc2: "Whether you're heading to a brunch with friends, a shopping spree, or a night out on the town, the Patso - Shoulder bag-White-Plain is your perfect companion. Its friendly and inviting design will make you feel confident and ready to take on the world. Don't miss out on this incredibly stylish, cool, and classy shoulder bag. Get your hands on the Patso - Shoulder bag-White-Plain today and make a fashion statement that will leave everyone in awe!"
    },

    {
        id: "flsh-00-23",
        category: "women's fashion",
        tags: "Women, Reebok, Sneakers",
        name: "Reebok - Women’s Powder sneakers",
        seller: "Reebok",
        isNew: true,
        price: 35999,
        oldPrice: 64700,
        discount: 25,
        stock: 8,
        ratings: 3.9,
        ratingsCount: 22,
        img: reebook,
        shipping: 2,
        quantity: 4,
        isShoe: true,
        size: 38,
        productNumber: 5,
        description: "Crafted with utmost precision and attention to detail, these sneakers are designed to elevate your style quotient to new heights.",
        desc: "The Women’s Powder Sneakers by Reebok are not only incredibly stylish but also exude an air of sophistication. With their sleek and modern design, they are the perfect choice for the fashion-conscious woman who seeks to make a statement wherever she goes. These sneakers boast a seamless blend of functionality and aesthetics. The premium quality materials used in their construction ensure durability and long-lasting performance, while the meticulous craftsmanship guarantees a comfortable fit that will keep your feet happy all day long. Whether you're heading to a casual outing with friends or a formal event, the Women’s Powder Sneakers will effortlessly complement any attire. Their versatile design allows you to effortlessly transition from day to night, making them a must-have addition to your footwear collection. In addition to their striking appearance, these sneakers are equipped with innovative features that enhance your overall experience.",
        desc2: "The cushioned insole provides exceptional support and comfort, while the sturdy outsole offers superior traction and stability, ensuring every step you take is confident and secure.  Reebok, a renowned name in the world of footwear, has once again created a masterpiece with the Women’s Powder Sneakers. Embrace the epitome of style and elegance with these sneakers that are sure to turn heads wherever you go."
    },

    {
        id: "flsh-00-24",
        category: "headphones",
        tags: "Gadgets, Music, Headphones",
        name: "Sony - WH-CH720N Wireless Noise Canceling",
        seller: "Sony",
        price: 49999,
        oldPrice: 122700,
        discount: 45,
        stock: 5,
        ratings: 4.1,
        ratingsCount: 32,
        img: beatz,
        shipping: 2,
        quantity: 4,
        description: "Picture this: you're strolling down the street, jamming to your favorite tunes, and suddenly you feel like you're in your own personal concert. The WH-CH720N headphones deliver mind-blowing sound quality that will make you want to break into an impromptu dance routine right then and there.",
        desc: "Introducing the Sony - WH-CH720N Wireless Headphones, the epitome of 'incredibly cool' in the world of audio gadgets! These earphones are here to revolutionize your music experience with a touch of humor and a whole lot of awesomeness. But it doesn't stop there, folks. These earphones are designed to fit like a dream, ensuring maximum comfort even during those marathon music sessions. Say goodbye to those annoying earaches and hello to a world of pure audio bliss. Plus, with their sleek and stylish design, you'll look effortlessly cool while rocking out to your favorite beats. Now, let's talk about the magical noise-canceling feature. Say adios to the hustle and bustle of the outside world as you immerse yourself in a bubble of musical euphoria. Whether you're on a crowded subway or trying to escape your chatty neighbor, these earphones will transport you to a serene audio sanctuary. It's like having your own personal mute button for the world around you! And did we mention the battery life? Brace yourselves, folks, because these earphones will keep the party going for up to 35 hours on a single charge.",
        desc2: "That's right, you can listen to your heart's content without worrying about running out of juice. It's like having a never-ending concert in your pocket! So, if you're ready to take your music experience to the next level and become the coolest cat in town, the Sony - WH-CH720N Wireless Earphones are here to make it happen. Get ready to rock, roll, and laugh your way through the day with these incredibly cool earphones. Trust us, your ears will thank you!"
    },

    {
        id: "flsh-00-25",
        category: "headphones",
        tags: "Gadgets, Headphones",
        name: "Skullcandy - Crusher anc 2 wireless headphones",
        seller: "Sony",
        price: 24400,
        oldPrice: 56999,
        discount: 33,
        stock: 10,
        ratings: 4.6,
        ratingsCount: 18,
        img: beatz2,
        shipping: 2,
        quantity: 17,
        description: "Introducing the Skullcandy - Crusher ANC 2 Wireless Headphones, the epitome of cool and style! These headphones are not just your ordinary audio gear; they are a statement of your passion for music and fashion.",
        desc: "With their sleek and modern design, the Skullcandy - Crusher ANC 2 Wireless Headphones are bound to turn heads wherever you go. Their incredible coolness factor is simply unmatched. Crafted with attention to detail, these headphones boast a unique aesthetic that sets you apart from the crowd. But it's not just about the looks; the Skullcandy - Crusher ANC 2 Wireless Headphones deliver an exceptional audio experience. Immerse yourself in the world of music with their powerful sound quality that brings your favorite tracks to life. Feel the deep bass rumble through your bones, making every beat resonate with your soul. These headphones are designed for the true music enthusiasts who demand nothing but the best. Equipped with advanced noise-canceling technology, the Skullcandy - Crusher ANC 2 Wireless Headphones block out unwanted distractions, allowing you to fully immerse yourself in your music.",
        desc2: "Say goodbye to outside noise and hello to pure audio bliss. Not only do these headphones sound incredible, but they also provide ultimate comfort. The plush ear cushions and adjustable headband ensure a perfect fit, even during long listening sessions. You can wear them for hours on end without any discomfort, allowing you to fully enjoy your music without any distractions."
    },

    {
        id: "flsh-00-26",
        category: "home & office",
        tags: "Home, Ofiice, Sitting room",
        name: "Loveseat Sofa",
        seller: "Sofa",
        price: 45500,
        oldPrice: 59999,
        discount: 30,
        stock: 6,
        ratings: 4.0,
        ratingsCount: 10,
        img: sofa,
        shipping: 2,
        quantity:14,
        description: "Introducing the Loveseat Sofa - an incredibly cool and stylish addition to your living space! This magnificent piece of furniture is designed to bring a touch of passion and sophistication to any room.",
        desc: "Crafted with utmost precision and attention to detail, the Loveseat Sofa boasts a sleek and modern design that is sure to turn heads. Its clean lines and smooth curves create an inviting and irresistible charm that will instantly elevate the ambiance of your home. But it's not just its stunning appearance that sets this loveseat apart. The Loveseat Sofa is also built for comfort, ensuring that you can relax and unwind in absolute bliss. Sink into its plush cushions and experience a level of coziness that is simply unmatched. Whether you're curling up with a good book, enjoying a movie night with loved ones, or simply indulging in some well-deserved me-time, the Loveseat Sofa provides the perfect spot to do so. Its generous seating space allows for intimate conversations or cozy cuddles, making it an ideal choice for couples or small families. Constructed with premium materials, this loveseat is not only incredibly durable but also easy to clean and maintain.",
        desc2: "Its sturdy frame ensures long-lasting support, while the high-quality upholstery adds a touch of luxury to your living area. With the Loveseat Sofa, you can effortlessly transform your living room, bedroom, or even office into a haven of style and comfort. So why settle for ordinary when you can have extraordinary? Elevate your space and make a statement with this incredibly cool and stylish Loveseat Sofa."
    },
    {
        id: "flsh-00-27",
        category: "phones",
        tags: "Phones, Iphone, Apple",
        name: "Iphone 14 Pro",
        seller: "Apple",
        price: 1260000,
        oldPrice: 1299999,
        discount: 39,
        stock: 16,
        ratings: 4.3,
        ratingsCount: 22,
        img: iphone,
        shipping: 2,
        quantity: 4,
        imgMark: [
            {
                imgMark1: iphone1,

            },
            
            {
                imgMark2: iphone2,
            },
            {
                imgMark3: iphone3,

            },
        ],
        description: "The iPhone 14 Pro and Pro Max feature a Super Retina XDR OLED display with a typical maximum brightness of 1,000 nits. However, it can go all the way up to 1,600 nits while watching HDR videos, and 2,000 nits outdoors. The display has a refresh rate of 120 Hz and utilizes LTPO technology.",
        desc: "Equipped with the latest technological advancements, the iPhone 14 Pro delivers an unrivaled performance that will leave you in awe. Powered by a lightning-fast processor, it effortlessly handles multitasking, gaming, and media consumption, providing a seamless and lag-free experience. Capture your precious moments like never before with the iPhone 14 Pro's state-of-the-art camera system. From breathtaking landscapes to stunning portraits, its advanced lenses and image processing capabilities ensure professional-grade photos and videos every time. Say goodbye to blurry shots and hello to picture-perfect memories. But what truly sets the iPhone 14 Pro apart is its affordability. Apple has made it their mission to bring premium features to a wider audience, and the iPhone 14 Pro is a testament to that commitment. With its competitive price tag, you can now enjoy the pinnacle of technology without breaking the bank. Stay connected and entertained throughout the day with the iPhone 14 Pro's long-lasting battery life and immersive display.",
        desc2: "Whether you're streaming your favorite shows, browsing the web, or staying in touch with loved ones, this device ensures uninterrupted usage, keeping you engaged and connected at all times. Incredibly cool, stylish, and affordable, the Apple iPhone 14 Pro is the ultimate smartphone that combines cutting-edge technology with a price that won't burn a hole in your pocket. Upgrade to the future of mobile innovation and experience a world of possibilities at your fingertips."
    },

]

